### PR TITLE
More progress on PyTorch acap device capture.

### LINKED ISSUE #78: Boxed kernel assertions
RuntimeError: false INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/core/boxing/impl/boxing.h":48, please report a bug to PyTorch. Tried to call KernelFunction::call() for a kernel that only has a boxed kernel and doesn't support calling from an unboxed API yet.

When hooking the dispatcher, not all kernels are supported with registration via a boxed fallback kernel. Need to special case/skip many of these. Moving out of the capture closure usually gets things moving for now.

### PR DESCRIPTION
**Pull request by stellaraccident**
* Now gets far enough to capture batch_norm.
* Has some issues still with in-place ops.
* Can materialize constants.
* Includes an upgrade to PyTorch nightly, which has important bug fixes for fallback and boxed kernel dispatch.
* Fixes #78, #79, #80.
* Will do more testing in a follow-up once further bugs are fixed that facilitate getting at the other features.

### CODE REVIEW

File: frontends/pytorch/csrc/c10_dispatch/acap_dispatch.cpp [hunk 1]
```diff
@@ -265,9 +273,85 @@ MlirType AcapController::mapIValueToMlirType(MlirLocation loc,
...
+    throw std::invalid_argument(msg.str());
+  };
+
+  // Get a C-contiguous form as we can bulk-load that into a DenseElementsAttr.
+  if (!tensor.is_contiguous())
+    tensor = tensor.contiguous();
+
+  // The flat number of bytes throws an exception for tensors that are not
+  // dense and accessible as such.
+  (void)tensor.nbytes();
```
Comment (silvasean) [inline frontends/pytorch/csrc/c10_dispatch/acap_dispatch.cpp:298]: They do have some facilities for this kind of assertions, e.g. at::check* functions:
https://github.com/llvm/mlir-npcomp/blob/b6bdc8cc4fcb555510901148afbc222735026662/tools/mnist-playground/mnist-playground.cpp#L79

**Review by silvasean — APPROVED** [review]
